# Generated by Django 4.1.3 on 2022-11-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_rename_group_trait"),
        ("pets", "0002_pet_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(
                null=True, related_name="pets", to="traits.trait"
            ),
        ),
    ]
