# Generated by Django 4.1.3 on 2022-11-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Trait",
        ),
    ]
